"""add profile_image_url to user

Revision ID: 9ea9210c6114
Revises: 280d1a42ee20
Create Date: 2026-07-27 21:40:33.591483+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '9ea9210c6114'
down_revision: str | None = '280d1a42ee20'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_image_url', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_image_url')
    # ### end Alembic commands ###
