"""Add is_default

Revision ID: a8285b20f7ed
Revises: f799a7e40d49
Create Date: 2026-07-26 10:15:56.796910+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = 'a8285b20f7ed'
down_revision: str | None = 'f799a7e40d49'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column('whatsapp_accounts', sa.Column('is_default', sa.Boolean(), server_default='false', nullable=False))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
